name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - card: stats
            options: username=${{ github.repository_owner }}&show_icons=true&theme=algolia
            path: profile/stats.svg
          - card: top-langs
            options: username=${{ github.repository_owner }}&theme=algolia
            path: profile/top-langs.svg
          - card: pin
            options: username=${{ github.repository_owner }}&repo=Yacht&theme=algolia
            path: profile/pin-yacht.svg
          - card: pin
            options: username=${{ github.repository_owner }}&repo=selfhosted_templates&theme=algolia
            path: profile/pin-selfhosted-templates.svg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: ${{ matrix.card }}
          options: ${{ matrix.options }}
          path: ${{ matrix.path }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push